name: Build PAWN project

on:
  push:
    branches: [ builds ]
    paths:
      - 'uploads_pawn/**'

jobs:
  build:
    runs-on: windows-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Run PAWN build
        shell: pwsh
        run: ./scripts/build_pawn.ps1
